import express from "express";
import { validateProduct } from "../middleware/validateProduct.js";
import { validatePatch } from "../middleware/validatePatch.js";
import { protect } from "../middleware/authMiddleware.js";
import { authorize } from "../middleware/authorize.js";
import { cache } from "../middleware/cache.js";
import { getAllProducts,getProductById , createProduct , modifyProduct , deleteProduct , patchProduct} from "../controllers/productControllers.js";
const router = express.Router();
router.get("/api/products" ,cache(60000), getAllProducts);
router.get("/api/product/:id",cache(60000) ,getProductById);
router.post("/api/products" ,protect,authorize("user") , validateProduct,createProduct);
router.put("/api/product/:id",protect,authorize("user"),validateProduct,modifyProduct);
router.delete("/api/product/:id",protect,authorize("admin"),deleteProduct);
router.patch("/api/product/:id" , protect,authorize("admin"),validatePatch,patchProduct);
export default router;